### ISSUE TITLE
Test the open --json folder field the skill teaches ("folder": {path, requested})

### ISSUE THREAD

**Issue by redtear1115** [redtear1115/mars-dawn-kit#103]
The agent skill (from 0.5.3) teaches agents that `marsdawn open --folder <path> --json` returns `"folder": {"path": ..., "requested": true}`, and the README says the same. Nothing in `Tests/` asserts that shape: a grep finds no test that checks the `folder` or `requested` fields. Today the claim rests on `Sources/marsdawn/Commands.swift` (the `fields["folder"] = ["path": folder.path, "requested": true]` line) and on a real run against the 1.0.0 (5) app on 2026-09-25.

Found as a P4 advisory while verifying #81.

## Done when

- A test pins the `--json` result of `open` with a folder, without launching an app. The existing open tests use a stub or `MARSDAWN_APP_PATH`; follow them.
  - `open --folder DIR FILE --json` prints `folder.path` (absolute) and `folder.requested == true`, with `opened` holding FILE.
  - `open DIR --json` prints the folder and an empty `opened`.
  - The same folder given as an argument and again with `--folder` gives one `folder` object.
- A red control: changing the field name, or dropping `requested`, fails the test.
- The skill's wording and the test agree. If the shape ever changes, the skill, README and website `/cli/agents/` change with it.

Not in scope: whether the sidebar actually shows the folder. That's `attached`, #69's work in 0.5.4.
